### ISSUE TITLE
Progression transfer tracking issue

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#463]
- [x] https://github.com/thepeacockproject/Peacock/issues/462
- [x] https://github.com/thepeacockproject/Peacock/issues/450
- [x] https://github.com/thepeacockproject/Peacock/issues/447
- [x] https://github.com/thepeacockproject/Peacock/issues/441
