### ISSUE TITLE
Tracking item rewards that have no challenges attached to them yet

### ISSUE THREAD

**Issue by Watchman3001** [thepeacockproject/Peacock#467]
**What**

- [x] Janus' Burial Dagger - challenge not implemented in peacock yet, existing on official - "Forged in Fire"

- [x] Golden Sawed Off Bartoli 12G - challenge not implemented in peacock yet, existing on official - "The Great Thief"

- [ ] All commemorative coins - tied to challenges on official regarding ETs of the past, in current state just available immediately in inventory. Might be tied to some Peacock exclusive challenges.

- [ ] All progress transfer items (Winter coat and travel briefcases) - available as Legacy Carryover on official, in current state just available immediately in inventory. Might be tied to some Peacock exclusive challenges

- [ ] Breaching charge MK2 - Apparently only exists in game files and available in peacock from the start. Might be tied to some Peacock exclusive challenges

- [ ] Solstice suit - Apparently only exists in game files and available in peacock from the start. Might be tied to some Peacock exclusive challenges

- [ ] Purple streak duck - Twitch reward,  in current state just available immediately in inventory. Might be tied to some Peacock exclusive challenges

- [x] Hokkaido elite patient kimono - Singular case of challenge being present and working, but not actually adding outfit to your loadout, reported before in #442 

**Why**
To make inventory and unlocks experience similar to official servers, especially in case of already existing challenges with item rewards

**Comment by suanjiansalt** [comment]
Basically the same thing with #172.
