### ISSUE TITLE
Release Checklist: v5.7.0

### ISSUE THREAD

**Issue by RDIL** [thepeacockproject/Peacock#89]
Scheduled date: 1-27-2023

- [x] Maintenance has started
    - [x] Put out announcement that maintenance has started
- [x] Server version bumped
    - [x] Bump server version in code
- [x] Update image pack
- [x] Update store data
- [x] Update unlockables
- [x] Add new gamechangers [SKIPPED FOR v6]
- [x] Add new entrances and agency pickups (If applicable)
- [ ] Add new entitlements
- [ ] Bump version
- [ ] Release the build
    - [ ] Announce release on Discord

Team: as per usual, feel free to modify to add any missing tasks, or to claim a task (put your @ next to a task)
